# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7430f1b03f7578cb31206b2cc74d59945516067e456b3bbcbc073320a6ac2bb0f820d244d37cd642c3862f886b4cd5d6b4d68aa69979eba09196651f23e3d73d

test:
  secret_key_base: 21e39dbab5f5536b92403cfabf9d0fddab974ef74942c1c5341c121005567f6cd9db35a0e442da266d82ac048dee1f99a05f7beca035e34d765a51cb9a7faa02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
